package:
  name: nqs_playground
  version: "0.0.1"
  build: 2

source:
  # git_url: https://github.com/twesterhout/nqs-playground
  # git_rev: develop
  path: /home/tom/tmp/nqs-playground


requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - cpuonly
    - pytorch {{ pytorch }}

  run:
    - numpy
    - cpuonly
    - {{ pin_compatible('pytorch', min_pin='x.x', max_pin='x.x') }}
    - typing-extensions
    - psutil
