package:
  name: nqs_playground
  version: "0.0.5"

source:
  # git_url: https://github.com/twesterhout/nqs-playground
  # git_rev: develop
  path: ../../
 
build:
  number: 1
  string: py{{ python }}_cuda{{ cudatoolkit }}_npy{{ numpy }}_torch{{ pytorch }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - _pytorch_select ==0.2
    - cudatoolkit {{ cudatoolkit }}
    - pytorch {{ pytorch }}

  run:
    - python
    - numpy
    - scipy
    - psutil
    - tensorboard >=2.0
    - _pytorch_select ==0.2
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - {{ pin_compatible('pytorch', min_pin='x.x.x', max_pin='x.x.x') }}
